### ISSUE TITLE
Uncaught TypeError: Cannot read property 'parentElement' of undefined

### ISSUE THREAD

**Issue by itraor** [thtliife/grammar-tab-colors#6]
[Enter steps to reproduce:]

1. Loaded the project on Atom
2. Started Ensime, then started to navigate the code
3. Pressed Cmd+Click on a case class, it lead me to this error

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [grammar-tab-colors](https://github.com/thtliife/grammar-tab-colors) package 0.2.8

### Stack Trace

Uncaught TypeError: Cannot read property 'parentElement' of undefined

```
At /Users/ivyrocks/.atom/packages/grammar-tab-colors/lib/grammar-tab-colors-utils.js:240

TypeError: Cannot read property 'parentElement' of undefined
    at Object.module.exports.decorateThisTabDiv (/packages/grammar-tab-colors/lib/grammar-tab-colors-utils.js:240:13)
    at /packages/grammar-tab-colors/lib/grammar-tab-colors.js:29:18
```

### Commands

```
     -2:53.7.0 core:confirm (input.hidden-input)
     -2:53.7.0 ensime:start (input.hidden-input)
     -2:37.9.0 settings-view:open (div.ensime-log-view.scroll-view.native-key-bindings)
     -1:27.2.0 command-palette:toggle (div.ensime-log-view.scroll-view.native-key-bindings)
     -1:24.5.0 core:backspace (input.hidden-input)
     -1:20.7.0 ensime:update-server (div.ensime-log-view.scroll-view.native-key-bindings)
     -1:12.6.0 application:add-project-folder (input.hidden-input)
     -1:10.3.0 command-palette:toggle (input.hidden-input)
     -1:08.3.0 core:move-down (input.hidden-input)
     -1:08.0 core:move-up (input.hidden-input)
     -1:07.8.0 core:confirm (input.hidden-input)
     -1:07.8.0 ensime:stop (input.hidden-input)
     -1:04.0 command-palette:toggle (input.hidden-input)
     -1:02.5.0 core:move-down (input.hidden-input)
     -1:02.2.0 core:confirm (input.hidden-input)
     -1:02.2.0 ensime:start (input.hidden-input)
```

### Non-Core Packages

```
api-workbench 0.8.46 
ariake-dark-syntax 0.1.3 
atom-clock 0.1.13 
atom-html-preview 0.1.22 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
autoclose-html 0.23.0 
autohide-tree-view 0.25.1 
browser-plus 0.0.98 
busy-signal 1.4.3 
Ensime 0.41.0 
go-find-references 1.2.3 
go-outline 0.6.6 
go-plus 5.5.5 
grammar-tab-colors 0.2.8 
html-to-css 0.2.2 
hyperclick 0.1.2 
intentions 1.1.2 
language-scala 1.1.8 
linter 2.2.0 
linter-ui-default 1.6.3 
linter-write-good 0.9.0 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
qolor 0.4.2 
smart-tab-name 1.0.5 
tree-view-open-files 0.3.0 
```

**Comment by thtliife** [comment]
Hi @itraor
Is this a persistent issue?
Are you able to reproduce it easily?

**Comment by itraor** [comment]
Yes it is a persistent issue. However, I was desperate for a solution, look around and came across this link http://ensime.org/editors/emacs/troubleshooting/ 

I followed the steps, literally. Ultimately, uninstalled Ensime, deleted everything except Atom, reinstalled Ensime, reloaded my project, started Ensime. The problem was gone.

So, although my resolution wasn't technical, I consider the issue solved. The case can be close.

**Comment by thtliife** [comment]
Thanks for the update @itraor 
I will close this issue as you appear to have gotten it sorted. :)
